carts/urls.py
from django.urls import path, re_path

from .views import (
    cart_home,
    cart_update,
    checkout_home, 
    checkout_done_view,
    )

urlpatterns = [
    path('',cart_home, name = 'home'),
    path('checkout/',checkout_home, name = 'checkout'),
    path('update/',cart_update, name = 'update'),
    path('checkout/success/',checkout_done_view, name = 'success'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView


from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import login_page, register_page, guest_register_view
from carts.views import cart_detail_api_view
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_page, name = 'home'),
    path('about/',views.about, name = 'about'),
    path('contact/',views.contact, name = 'contact'),
    path('login/',login_page, name = 'login'),
    path('checkout/address/create/',checkout_address_create_view, name = 'checkout_address_create'),
    path('checkout/address/reuse/',checkout_address_reuse_view, name = 'checkout_address_reuse'),
    path('register/guest',guest_register_view, name = 'guest_register'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',register_page, name = 'register'),
    path('bootstrap/',TemplateView.as_view(template_name ='bootstrap/example.html')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    path('cart/', include(("carts.urls", 'cart'), namespace='cart')),
    path('api/cart/',cart_detail_api_view, name = 'api_cart'),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, re_path

from .views import (
    ProductListView,
    ProductDetailSlugView,
    )

urlpatterns = [
    path('',ProductListView.as_view(), name = 'list'),
    re_path(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(), name = 'detail'),

]

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- <link rel='stylesheet' href='{% static "css/main.css" %}'> -->

<!-- Font Awesome CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<!-- navbar-light bg-dark mb-3 -->
<nav class="navbar navbar-expand-lg ">
	<div class="container">
  <a class="navbar-brand" href="{{ home_url }}"><img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">{% if brand_name %} {{ brand_name }} {% else %} CPP eCommerce {% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{{ about_url }}">About</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link " href="{{ product_list_url }}">Product</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link " href="{{ logout_url }}">Logout</a>
      {% else %}
      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link " href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link " href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link " href="{{ cart_url }}"><span class="navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden='true'></i></a>
      </li>
<!--       <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown link
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
              </li> -->
    </ul>
    {% include 'search/snippets/searchform.html' %}
<!--     <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
  </div>
</nav>